# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).

{ config, lib, pkgs, inputs, ... }:

{
	imports = [
		# Include the results of the hardware scan. This should be generated by nixos-generate-config
		./hardware-configuration.nix
	];

	nix.settings.experimental-features = [ "nix-command" "flakes" ];

	baseDirectory = "/etc/nixos";

	system.audio.enable = true;

	system.boot.enable = true;
	system.boot.efi = false;
	system.boot.device = "/dev/sda";
	system.boot.theme.enable = true;

	system.networking.enable = true;
	system.networking.host = "bertor";
	system.networking.allowedTCPPorts = lib.range 8000 8100;

	system.virtualization.enable = true;
	system.virtualization.program = "vmware";
	system.virtualization.audio.legacyIntel = true;
	system.virtualization.sharedFolders = [
		{
			directory = "/vmshare";
			device = "Shared";
		}
	];

	system.time.enable = true;
	system.time.timeZone = "Asia/Kolkata";

	graphical.enable = true;

	user.enable = true;
	user.users = [
		{
			username = "arpit";
			wheel = true;
		}
	];

	# This option defines the first version of NixOS you have installed on this particular machine,
	# and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
	#
	# Most users should NEVER change this value after the initial install, for any reason,
	# even if you've upgraded your system to a new NixOS release.
	#
	# This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
	# so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
	# to actually do that.
	#
	# This value being lower than the current NixOS release does NOT mean your system is
	# out of date, out of support, or vulnerable.
	#
	# Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
	# and migrated your data accordingly.
	#
	# For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
	system.stateVersion = "25.05"; # Did you read the comment?
}

